---
title: "Week_8"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter 7 Maps

```{r}
location <- c("lunch", "view")
addr <- c( "10 Main Street, Middletown, CT",
           "20 W 34th St., New York, NY, 10001")
df <- data.frame(location, addr)
```

```{r}
library(tidygeocoder)
df <- tidygeocoder::geocode(df, address = addr, method = "osm")
```

```{r}
library(ggmap)

# subset the data
library(dplyr)
homicide <- filter(crime, offense == "murder") %>%
  select(date, offense, address, lon, lat)

# view data
head(homicide, 3)
```

```{r}
library(mapview)
library(sf)
mymap <- st_as_sf(homicide, coords = c("lon", "lat"), crs = 4326)
mapview(mymap)
```

```{r}
library(sf)
library(mapview)
mymap <- st_as_sf(homicide, coords = c("lon", "lat"), crs = 4326)
mapview(mymap, color="black", col.regions="red",
        alpha.regions=0.5, legend = FALSE,
        homebutton = FALSE, map.types = "OpenStreetMap" )
```

```{r}
# create leaflet graph
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=-72.6560002,
             lat=41.5541829,
             popup="The birthplace of quantitative wisdom.</br>
             No, Waldo is not here.")
```

```{r}
ggmap::register_stadiamaps("your API key")
```

```{r}
# find a bounding box for Houston, Texas
library(osmdata)
bb <- getbb("houston, tx")
bb
```

```{r}
library(ggmap)
houston <- get_stadiamap(bbox = c(bb[1,1], bb[2,1], 
                                  bb[1,2], bb[2,2]),
                         maptype="stamen_toner_lite")
ggmap(houston)
```

```{r}
# add incident locations
ggmap(houston) +
  geom_point(aes(x=lon,y=lat),data=homicide,
             color = "red", size = 2, alpha = 0.5)
```

```{r}
# remove long and lat numbers and add titles
ggmap(houston) +
  geom_point(aes(x=lon,y=lat),data=homicide,
             color = "red", size = 2, alpha = 0.5) +
  theme_void() +
  labs(title = "Location of reported homocides",
       subtitle = "Houston Jan - Aug 2010",
       caption = "source: http://www.houstontx.gov/police/cs/")
```

```{r}
library(ggmap)
# using geocode function to obtain the center coordinates
register_google(key="PutYourGoogleAPIKeyHere")
houston_center <- geocode("Houston, TX")
```

```{r}
houston_center
```

```{r}
# get Houston map
houston_map <- get_map(houston_center, 
                       zoom = 13, 
                       maptype = "roadmap")
ggmap(houston_map)
```

```{r}
# add incident locations
ggmap(houston_map) +
  geom_point(aes(x=lon,y=lat),data=homicide,
             color = "red", size = 2, alpha = 0.5)
```

```{r}
# add incident locations
ggmap(houston_map) +
  geom_point(aes(x=lon,y=lat),data=homicide,
             color = "red", size = 2, alpha = 0.5) +
  theme_void() +
  labs(title = "Location of reported homocides",
       subtitle = "Houston Jan - Aug 2010",
       caption = "source: http://www.houstontx.gov/police/cs/")
```

```{r}
# view the first 12 region names in country.map
data(country.map, package = "choroplethrMaps")
head(unique(country.map$region), 12)
```

```{r}
# prepare dataset
data(gapminder, package = "gapminder")
plotdata <- gapminder %>%
  filter(year == 2007) %>%
  rename(region = country,
         value = lifeExp) %>%
  mutate(region = tolower(region)) %>%
  mutate(region = 
    recode(region,
          "united states"    = "united states of america",
          "congo, dem. rep." = "democratic republic of the congo",
          "congo, rep."      = "republic of congo",
          "korea, dem. rep." = "south korea",
          "korea. rep."      = "north korea",
          "tanzania"         = "united republic of tanzania",
          "serbia"           = "republic of serbia",
          "slovak republic"  = "slovakia",
          "yemen, rep."      = "yemen"))
```

```{r}
library(choroplethr)
country_choropleth(plotdata)
```

```{r}
country_choropleth(plotdata,
                   num_colors=9) +
  scale_fill_brewer(palette="YlOrRd") +
  labs(title = "Life expectancy by country",
       subtitle = "Gapminder 2007 data",
       caption = "source: https://www.gapminder.org",
       fill = "Years")
```

```{r}
library(ggplot2)
library(choroplethr)
data(continental_us_states)

# input the data
library(readr)
hisplat <- read_tsv("hisplat.csv")

# prepare the data
hisplat$region <- tolower(hisplat$state)
hisplat$value <- hisplat$percent

# create the map
state_choropleth(hisplat, 
                 num_colors=9,
                 zoom = continental_us_states) +
  scale_fill_brewer(palette="YlGnBu") +
  labs(title = "Hispanic and Latino Population",
       subtitle = "2010 US Census",
       caption = "source: https://tinyurl.com/2fp7c5bw",
       fill = "Percent") 
```

```{r}
library(ggplot2)
library(choroplethr)
library(dplyr)

# enter violent crime rates by county
crimes_ct <- data.frame(
  county = c("fairfield", "hartford", 
             "litchfield", "middlesex", 
             "new haven", "new london", 
             "tolland", "windham"),
  value = c(3.00, 3.32, 
            1.02, 1.24, 
            4.13, 4.61, 
            0.16, 1.60)
)

crimes_ct
```

```{r}
# obtain region codes for connecticut
data(county.regions, 
     package = "choroplethrMaps")
region <- county.regions %>%
  filter(state.name == "connecticut")

region
```

```{r}
# join crime data to region code data
plotdata <- inner_join(crimes_ct, 
                       region, 
                       by=c("county" = "county.name"))
plotdata
```

```{r}
# create choropleth map
county_choropleth(plotdata, 
                  state_zoom = "connecticut",
                  reference_map = TRUE,
                  num_colors = 8) +
  scale_fill_brewer(palette="YlOrRd") +
  labs(title = "Connecticut Violent Crime Rates",
       subtitle = "FBI 2012 data",
       caption = "source: https://ucr.fbi.gov",
       fill = "Violent Crime\n Rate Per 1000")
```

```{r}
library(sf)
# unzip shape file
shapefile <- "cb_2022_us_state_20m.zip"
shapedir  <- tools::file_path_sans_ext(shapefile)
if(!dir.exists(shapedir)){
  unzip(shapefile, exdir=shapedir)
}

# convert the shapefile into a data frame 
# of class sf (simple features)
USMap <- st_read("cb_2022_us_state_20m/cb_2022_us_state_20m.shp")
```

```{r}
head(USMap, 3)
```

```{r}
litRates <- read.csv("USLitRates.csv")
head(litRates, 3)
```

```{r}
# states in litRates not in USMap
setdiff(litRates$State, USMap$NAME)
```

```{r}
continentalUS <- USMap %>% 
  left_join(litRates, by=c("NAME"="State")) %>%
  filter(NAME != "Hawaii" & NAME != "Alaska" & 
           NAME != "Puerto Rico")
head(continentalUS, 3)
```

```{r}
library(ggplot2)
ggplot(continentalUS, aes(geometry=geometry, fill=Rate)) +
  geom_sf()
```

```{r}
library(dplyr)
ggplot(continentalUS, aes(geometry=geometry, fill=Rate)) +
  geom_sf() +
  theme_void() +
  geom_sf_text(aes(label=STUSPS), size=2) +
  scale_fill_steps(low="yellow", high="royalblue", 
                   n.breaks = 10) +
  labs(title="Literacy Rates by State",
       fill = "% literate",
       x = "", y = "",
       subtitle="Updated May 2023",
       caption="source: https://worldpopulationreview.com")
```

# Chapter 8 Time-dependent graphs

```{r}
library(ggplot2)
ggplot(economics, aes(x = date, y = psavert)) +
  geom_line() +
  labs(title = "Personal Savings Rate",
       x = "Date",
       y = "Personal Savings Rate")
```

```{r}
library(ggplot2)
library(scales)
ggplot(economics, aes(x = date, y = psavert)) +
  geom_line(color = "indianred3", 
            size=1 ) +
  geom_smooth() +
  scale_x_date(date_breaks = '5 years', 
               labels = date_format("%b-%y")) +
  labs(title = "Personal Savings Rate",
       subtitle = "1967 to 2015",
       x = "",
       y = "Personal Savings Rate") +
  theme_minimal()
```

```{r}
# multivariate time series

# one time install
# install.packages("quantmod")

library(quantmod)
library(dplyr)

# get apple (AAPL) closing prices
apple <- getSymbols("AAPL", 
                    return.class = "data.frame", 
                    from="2023-01-01")

apple <- AAPL %>% 
  mutate(Date = as.Date(row.names(.))) %>%
  select(Date, AAPL.Close) %>%
  rename(Close = AAPL.Close) %>%
  mutate(Company = "Apple")

# get Meta (META) closing prices
meta <- getSymbols("META", 
                   return.class = "data.frame", 
                   from="2023-01-01")

meta <- META %>% 
  mutate(Date = as.Date(row.names(.))) %>%
  select(Date, META.Close) %>%
  rename(Close = META.Close) %>%
  mutate(Company = "Meta")

# combine data for both companies
mseries <- rbind(apple, meta)

# plot data
library(ggplot2)
ggplot(mseries, 
       aes(x=Date, y= Close, color=Company)) + 
  geom_line(size=1) +
  scale_x_date(date_breaks = '1 month', 
               labels = scales::date_format("%b")) +
  scale_y_continuous(limits = c(120, 280), 
                     breaks = seq(120, 280, 20),
                     labels = scales::dollar) +
  labs(title = "NASDAQ Closing Prices",
       subtitle = "Jan - June 2023",
       caption = "source: Yahoo Finance",
       y = "Closing Price") +
  theme_minimal() +
  scale_color_brewer(palette = "Dark2")
```

```{r}
library(ggalt)
library(tidyr)
library(dplyr)

# load data
data(gapminder, package = "gapminder")

# subset data
plotdata_long <- filter(gapminder,
                        continent == "Americas" &
                        year %in% c(1952, 2007)) %>%
  select(country, year, lifeExp)

# convert data to wide format
plotdata_wide <- pivot_wider(plotdata_long, 
                             names_from = year, 
                             values_from = lifeExp)
names(plotdata_wide) <- c("country", "y1952", "y2007")

# create dumbbell plot
ggplot(plotdata_wide, aes(y = country,
                          x = y1952,
                          xend = y2007)) +  
  geom_dumbbell()
```

```{r}
# create dumbbell plot
ggplot(plotdata_wide, 
       aes(y = reorder(country, y1952),
           x = y1952,
           xend = y2007)) +  
  geom_dumbbell(size = 1.2,
                size_x = 3, 
                size_xend = 3,
                colour = "grey", 
                colour_x = "red", 
                colour_xend = "blue") +
  theme_minimal() + 
  labs(title = "Change in Life Expectancy",
       subtitle = "1952 to 2007",
       x = "Life Expectancy (years)",
       y = "")
```

```{r}
library(CGPfunctions)

# Select Central American countries data 
# for 1992, 1997, 2002, and 2007

df <- gapminder %>%
  filter(year %in% c(1992, 1997, 2002, 2007) &
           country %in% c("Panama", "Costa Rica", 
                          "Nicaragua", "Honduras", 
                          "El Salvador", "Guatemala",
                          "Belize")) %>%
  mutate(year = factor(year),
         lifeExp = round(lifeExp)) 

# create slope graph

newggslopegraph(df, year, lifeExp, country) +
  labs(title="Life Expectancy by Country", 
       subtitle="Central America", 
       caption="source: gapminder")
```

```{r}
# basic area chart
ggplot(economics, aes(x = date, y = psavert)) +
  geom_area(fill="lightblue", color="black") +
  labs(title = "Personal Savings Rate",
       x = "Date",
       y = "Personal Savings Rate")
```

```{r}
# stacked area chart
data(uspopage, package = "gcookbook")
ggplot(uspopage, aes(x = Year,
                     y = Thousands, 
                     fill = AgeGroup)) +
  geom_area() +
  labs(title = "US Population by age",
       x = "Year",
       y = "Population in Thousands")
```

```{r}
# stacked area chart
data(uspopage, package = "gcookbook")
ggplot(uspopage, aes(x = Year,
                     y = Thousands/1000, 
                     fill = forcats::fct_rev(AgeGroup))) +
  geom_area(color = "black") +
  labs(title = "US Population by age",
       subtitle = "1900 to 2002",
       caption = "source: U.S. Census Bureau, 2003, HS-3",
       x = "Year",
       y = "Population in Millions",
       fill = "Age Group") +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal()
```

```{r}
# basic stream graph
data(uspopage, package = "gcookbook")
library(ggstream)
ggplot(uspopage, aes(x = Year,
                     y = Thousands/1000, 
                     fill = forcats::fct_rev(AgeGroup))) +
  geom_stream() +
  labs(title = "US Population by age",
       subtitle = "1900 to 2002",
       caption = "source: U.S. Census Bureau, 2003, HS-3",
       x = "Year",
       y = "",
       fill = "Age Group") +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.y = element_blank())
```

```{r}
# basic stream graph
data(uspopage, package = "gcookbook")
library(ggstream)
ggplot(uspopage, aes(x = Year,
                     y = Thousands/1000, 
                     fill = forcats::fct_rev(AgeGroup))) +
  geom_stream(type="proportional") +
  labs(title = "US Population by age",
       subtitle = "1900 to 2002",
       caption = "source: U.S. Census Bureau, 2003, HS-3",
       x = "Year",
       y = "Proportion",
       fill = "Age Group") +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() 
```
