---
title: "Week_12"
output: html_document
date: "2023-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **6 Topic modeling**

```{r}
library(topicmodels)

data("AssociatedPress")
AssociatedPress
#> <<DocumentTermMatrix (documents: 2246, terms: 10473)>>
#> Non-/sparse entries: 302031/23220327
#> Sparsity           : 99%
#> Maximal term length: 18
#> Weighting          : term frequency (tf)
```

```{r}
# set a seed so that the output of the model is predictable
ap_lda <- LDA(AssociatedPress, k = 2, control = list(seed = 1234))
ap_lda
#> A LDA_VEM topic model with 2 topics.
```

```{r}
library(tidytext)

ap_topics <- tidy(ap_lda, matrix = "beta")
ap_topics
#> # A tibble: 20,946 × 3
#>    topic term           beta
#>    <int> <chr>         <dbl>
#>  1     1 aaron      1.69e-12
#>  2     2 aaron      3.90e- 5
#>  3     1 abandon    2.65e- 5
#>  4     2 abandon    3.99e- 5
#>  5     1 abandoned  1.39e- 4
#>  6     2 abandoned  5.88e- 5
#>  7     1 abandoning 2.45e-33
#>  8     2 abandoning 2.34e- 5
#>  9     1 abbott     2.13e- 6
#> 10     2 abbott     2.97e- 5
#> # … with 20,936 more rows
```

```{r}
library(ggplot2)
library(dplyr)

ap_top_terms <- ap_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

ap_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

```{r}
library(tidyr)

beta_wide <- ap_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  pivot_wider(names_from = topic, values_from = beta) %>% 
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))

beta_wide
#> # A tibble: 198 × 4
#>    term              topic1      topic2 log_ratio
#>    <chr>              <dbl>       <dbl>     <dbl>
#>  1 administration 0.000431  0.00138         1.68 
#>  2 ago            0.00107   0.000842       -0.339
#>  3 agreement      0.000671  0.00104         0.630
#>  4 aid            0.0000476 0.00105         4.46 
#>  5 air            0.00214   0.000297       -2.85 
#>  6 american       0.00203   0.00168        -0.270
#>  7 analysts       0.00109   0.000000578   -10.9  
#>  8 area           0.00137   0.000231       -2.57 
#>  9 army           0.000262  0.00105         2.00 
#> 10 asked          0.000189  0.00156         3.05 
#> # … with 188 more rows
```

```{r}
ap_documents <- tidy(ap_lda, matrix = "gamma")
ap_documents
#> # A tibble: 4,492 × 3
#>    document topic    gamma
#>       <int> <int>    <dbl>
#>  1        1     1 0.248   
#>  2        2     1 0.362   
#>  3        3     1 0.527   
#>  4        4     1 0.357   
#>  5        5     1 0.181   
#>  6        6     1 0.000588
#>  7        7     1 0.773   
#>  8        8     1 0.00445 
#>  9        9     1 0.967   
#> 10       10     1 0.147   
#> # … with 4,482 more rows
```

```{r}
tidy(AssociatedPress) %>%
  filter(document == 6) %>%
  arrange(desc(count))
#> # A tibble: 287 × 3
#>    document term           count
#>       <int> <chr>          <dbl>
#>  1        6 noriega           16
#>  2        6 panama            12
#>  3        6 jackson            6
#>  4        6 powell             6
#>  5        6 administration     5
#>  6        6 economic           5
#>  7        6 general            5
#>  8        6 i                  5
#>  9        6 panamanian         5
#> 10        6 american           4
#> # … with 277 more rows
```

```{r}
titles <- c("Twenty Thousand Leagues under the Sea", 
            "The War of the Worlds",
            "Pride and Prejudice", 
            "Great Expectations")
```

```{r}
library(gutenbergr)

books <- gutenberg_works(title %in% titles) %>%
  gutenberg_download(meta_fields = "title")
```

```{r}
library(stringr)

# divide into documents, each representing one chapter
by_chapter <- books %>%
  group_by(title) %>%
  mutate(chapter = cumsum(str_detect(
    text, regex("^chapter ", ignore_case = TRUE)
  ))) %>%
  ungroup() %>%
  filter(chapter > 0) %>%
  unite(document, title, chapter)

# split into words
by_chapter_word <- by_chapter %>%
  unnest_tokens(word, text)

# find document-word counts
word_counts <- by_chapter_word %>%
  anti_join(stop_words) %>%
  count(document, word, sort = TRUE)

word_counts
#> # A tibble: 104,721 × 3
#>    document                 word        n
#>    <chr>                    <chr>   <int>
#>  1 Great Expectations_57    joe        88
#>  2 Great Expectations_7     joe        70
#>  3 Great Expectations_17    biddy      63
#>  4 Great Expectations_27    joe        58
#>  5 Great Expectations_38    estella    58
#>  6 Great Expectations_2     joe        56
#>  7 Great Expectations_23    pocket     53
#>  8 Great Expectations_15    joe        50
#>  9 Great Expectations_18    joe        50
#> 10 The War of the Worlds_16 brother    50
#> # … with 104,711 more rows
```

```{r}
chapters_dtm <- word_counts %>%
  cast_dtm(document, word, n)

chapters_dtm
#> <<DocumentTermMatrix (documents: 193, terms: 18215)>>
#> Non-/sparse entries: 104721/3410774
#> Sparsity           : 97%
#> Maximal term length: 19
#> Weighting          : term frequency (tf)
```

```{r}
chapters_lda <- LDA(chapters_dtm, k = 4, control = list(seed = 1234))
chapters_lda
#> A LDA_VEM topic model with 4 topics.
```

```{r}
chapter_topics <- tidy(chapters_lda, matrix = "beta")
chapter_topics
#> # A tibble: 72,860 × 3
#>    topic term        beta
#>    <int> <chr>      <dbl>
#>  1     1 joe     5.83e-17
#>  2     2 joe     3.19e-57
#>  3     3 joe     4.16e-24
#>  4     4 joe     1.45e- 2
#>  5     1 biddy   7.85e-27
#>  6     2 biddy   4.67e-69
#>  7     3 biddy   2.26e-46
#>  8     4 biddy   4.77e- 3
#>  9     1 estella 3.83e- 6
#> 10     2 estella 5.32e-65
#> # … with 72,850 more rows
```

```{r}
top_terms <- chapter_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 5) %>% 
  ungroup() %>%
  arrange(topic, -beta)

top_terms
#> # A tibble: 20 × 3
#>    topic term         beta
#>    <int> <chr>       <dbl>
#>  1     1 elizabeth 0.0141 
#>  2     1 darcy     0.00881
#>  3     1 miss      0.00871
#>  4     1 bennet    0.00695
#>  5     1 jane      0.00650
#>  6     2 captain   0.0155 
#>  7     2 nautilus  0.0131 
#>  8     2 sea       0.00885
#>  9     2 nemo      0.00871
#> 10     2 ned       0.00803
#> 11     3 people    0.00680
#> 12     3 martians  0.00651
#> 13     3 time      0.00535
#> 14     3 black     0.00528
#> 15     3 night     0.00448
#> 16     4 joe       0.0145 
#> 17     4 time      0.00685
#> 18     4 pip       0.00682
#> 19     4 looked    0.00637
#> 20     4 miss      0.00623
```

```{r}
chapters_gamma <- tidy(chapters_lda, matrix = "gamma")
chapters_gamma
#> # A tibble: 772 × 3
#>    document                 topic     gamma
#>    <chr>                    <int>     <dbl>
#>  1 Great Expectations_57        1 0.0000135
#>  2 Great Expectations_7         1 0.0000147
#>  3 Great Expectations_17        1 0.0000212
#>  4 Great Expectations_27        1 0.0000192
#>  5 Great Expectations_38        1 0.354    
#>  6 Great Expectations_2         1 0.0000172
#>  7 Great Expectations_23        1 0.551    
#>  8 Great Expectations_15        1 0.0168   
#>  9 Great Expectations_18        1 0.0000127
#> 10 The War of the Worlds_16     1 0.0000108
#> # … with 762 more rows
```

```{r}
chapters_gamma <- chapters_gamma %>%
  separate(document, c("title", "chapter"), sep = "_", convert = TRUE)

chapters_gamma
#> # A tibble: 772 × 4
#>    title                 chapter topic     gamma
#>    <chr>                   <int> <int>     <dbl>
#>  1 Great Expectations         57     1 0.0000135
#>  2 Great Expectations          7     1 0.0000147
#>  3 Great Expectations         17     1 0.0000212
#>  4 Great Expectations         27     1 0.0000192
#>  5 Great Expectations         38     1 0.354    
#>  6 Great Expectations          2     1 0.0000172
#>  7 Great Expectations         23     1 0.551    
#>  8 Great Expectations         15     1 0.0168   
#>  9 Great Expectations         18     1 0.0000127
#> 10 The War of the Worlds      16     1 0.0000108
#> # … with 762 more rows
```

```{r}
# reorder titles in order of topic 1, topic 2, etc before plotting
chapters_gamma %>%
  mutate(title = reorder(title, gamma * topic)) %>%
  ggplot(aes(factor(topic), gamma)) +
  geom_boxplot() +
  facet_wrap(~ title) +
  labs(x = "topic", y = expression(gamma))
```

```{r}
chapter_classifications <- chapters_gamma %>%
  group_by(title, chapter) %>%
  slice_max(gamma) %>%
  ungroup()

chapter_classifications
#> # A tibble: 193 × 4
#>    title              chapter topic gamma
#>    <chr>                <int> <int> <dbl>
#>  1 Great Expectations       1     4 0.821
#>  2 Great Expectations       2     4 1.00 
#>  3 Great Expectations       3     4 0.687
#>  4 Great Expectations       4     4 1.00 
#>  5 Great Expectations       5     4 0.782
#>  6 Great Expectations       6     4 1.00 
#>  7 Great Expectations       7     4 1.00 
#>  8 Great Expectations       8     4 0.686
#>  9 Great Expectations       9     4 0.992
#> 10 Great Expectations      10     4 1.00 
#> # … with 183 more rows
```

```{r}
book_topics <- chapter_classifications %>%
  count(title, topic) %>%
  group_by(title) %>%
  slice_max(n, n = 1) %>% 
  ungroup() %>%
  transmute(consensus = title, topic)

chapter_classifications %>%
  inner_join(book_topics, by = "topic") %>%
  filter(title != consensus)
#> # A tibble: 2 × 5
#>   title              chapter topic gamma consensus            
#>   <chr>                <int> <int> <dbl> <chr>                
#> 1 Great Expectations      23     1 0.551 Pride and Prejudice  
#> 2 Great Expectations      54     3 0.480 The War of the Worlds
```

```{r}
assignments <- augment(chapters_lda, data = chapters_dtm)
assignments
#> # A tibble: 104,721 × 4
#>    document              term  count .topic
#>    <chr>                 <chr> <dbl>  <dbl>
#>  1 Great Expectations_57 joe      88      4
#>  2 Great Expectations_7  joe      70      4
#>  3 Great Expectations_17 joe       5      4
#>  4 Great Expectations_27 joe      58      4
#>  5 Great Expectations_2  joe      56      4
#>  6 Great Expectations_23 joe       1      4
#>  7 Great Expectations_15 joe      50      4
#>  8 Great Expectations_18 joe      50      4
#>  9 Great Expectations_9  joe      44      4
#> 10 Great Expectations_13 joe      40      4
#> # … with 104,711 more rows
```

```{r}
assignments <- assignments %>%
  separate(document, c("title", "chapter"), 
           sep = "_", convert = TRUE) %>%
  inner_join(book_topics, by = c(".topic" = "topic"))

assignments
#> # A tibble: 104,721 × 6
#>    title              chapter term  count .topic consensus         
#>    <chr>                <int> <chr> <dbl>  <dbl> <chr>             
#>  1 Great Expectations      57 joe      88      4 Great Expectations
#>  2 Great Expectations       7 joe      70      4 Great Expectations
#>  3 Great Expectations      17 joe       5      4 Great Expectations
#>  4 Great Expectations      27 joe      58      4 Great Expectations
#>  5 Great Expectations       2 joe      56      4 Great Expectations
#>  6 Great Expectations      23 joe       1      4 Great Expectations
#>  7 Great Expectations      15 joe      50      4 Great Expectations
#>  8 Great Expectations      18 joe      50      4 Great Expectations
#>  9 Great Expectations       9 joe      44      4 Great Expectations
#> 10 Great Expectations      13 joe      40      4 Great Expectations
#> # … with 104,711 more rows
```

```{r}
library(scales)

assignments %>%
  count(title, consensus, wt = count) %>%
  mutate(across(c(title, consensus), ~str_wrap(., 20))) %>%
  group_by(title) %>%
  mutate(percent = n / sum(n)) %>%
  ggplot(aes(consensus, title, fill = percent)) +
  geom_tile() +
  scale_fill_gradient2(high = "darkred", label = percent_format()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid = element_blank()) +
  labs(x = "Book words were assigned to",
       y = "Book words came from",
       fill = "% of assignments")
```

```{r}
wrong_words <- assignments %>%
  filter(title != consensus)

wrong_words
#> # A tibble: 4,535 × 6
#>    title                                 chapter term     count .topic consensus
#>    <chr>                                   <int> <chr>    <dbl>  <dbl> <chr>    
#>  1 Great Expectations                         38 brother      2      1 Pride an…
#>  2 Great Expectations                         22 brother      4      1 Pride an…
#>  3 Great Expectations                         23 miss         2      1 Pride an…
#>  4 Great Expectations                         22 miss        23      1 Pride an…
#>  5 Twenty Thousand Leagues under the Sea       8 miss         1      1 Pride an…
#>  6 Great Expectations                         31 miss         1      1 Pride an…
#>  7 Great Expectations                          5 sergeant    37      1 Pride an…
#>  8 Great Expectations                         46 captain      1      2 Twenty T…
#>  9 Great Expectations                         32 captain      1      2 Twenty T…
#> 10 The War of the Worlds                      17 captain      5      2 Twenty T…
#> # … with 4,525 more rows

wrong_words %>%
  count(title, consensus, term, wt = count) %>%
  ungroup() %>%
  arrange(desc(n))
#> # A tibble: 3,500 × 4
#>    title              consensus             term         n
#>    <chr>              <chr>                 <chr>    <dbl>
#>  1 Great Expectations Pride and Prejudice   love        44
#>  2 Great Expectations Pride and Prejudice   sergeant    37
#>  3 Great Expectations Pride and Prejudice   lady        32
#>  4 Great Expectations Pride and Prejudice   miss        26
#>  5 Great Expectations The War of the Worlds boat        25
#>  6 Great Expectations Pride and Prejudice   father      19
#>  7 Great Expectations The War of the Worlds water       19
#>  8 Great Expectations Pride and Prejudice   baby        18
#>  9 Great Expectations Pride and Prejudice   flopson     18
#> 10 Great Expectations Pride and Prejudice   family      16
#> # … with 3,490 more rows
```

```{r}
word_counts %>%
  filter(word == "flopson")
#> # A tibble: 3 × 3
#>   document              word        n
#>   <chr>                 <chr>   <int>
#> 1 Great Expectations_22 flopson    10
#> 2 Great Expectations_23 flopson     7
#> 3 Great Expectations_33 flopson     1
```

```{r}
library(mallet)

# create a vector with one string per chapter
collapsed <- by_chapter_word %>%
  anti_join(stop_words, by = "word") %>%
  mutate(word = str_replace(word, "'", "")) %>%
  group_by(document) %>%
  summarize(text = paste(word, collapse = " "))

# create an empty file of "stopwords"
file.create(empty_file <- tempfile())
docs <- mallet.import(collapsed$document, collapsed$text, empty_file)

mallet_model <- MalletLDA(num.topics = 4)
mallet_model$loadDocuments(docs)
mallet_model$train(100)
```

```{r}
# word-topic pairs
tidy(mallet_model)

# document-topic pairs
tidy(mallet_model, matrix = "gamma")

# column needs to be named "term" for "augment"
term_counts <- rename(word_counts, term = word)
augment(mallet_model, term_counts)
```
